name: concesionaria-tec

networks:
  concesionaria-net:
    driver: bridge

services:
  # Base de datos SQL Server
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: concesionaria_db
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SqlS3rv3r_2026!
      - MSSQL_PID=Developer
      - MSSQL_AGENT_ENABLED=True
    ports:
      - "${DB_PORT:-1433}:1433"
    networks:
      - concesionaria-net
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./init.sql:/tmp/init.sql
      - ./jobs.sql:/tmp/jobs.sql
      - ./backups:/var/opt/mssql/backups
    command: |
      sh -c "
      /opt/mssql/bin/sqlservr &
      sleep 20
      echo 'Iniciando carga de base de datos y datos de prueba...'
      /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'SqlS3rv3r_2026!' -C -i /tmp/init.sql
      echo 'Iniciando configuracion de Jobs del Agente...'
      /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'SqlS3rv3r_2026!' -C -i /tmp/jobs.sql
      echo '¡Base de datos lista!'
      wait
      "
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "SqlS3rv3r_2026!" -C -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s

  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: concesionaria_backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://db:1433;databaseName=ConcesionariaTec;encrypt=true;trustServerCertificate=true;
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.SQLServerDialect
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    networks:
      - concesionaria-net
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: concesionaria_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT:-8081}:80"
    networks:
      - concesionaria-net

volumes:
  sqlserver_data: